### ISSUE TITLE
trans-agent failes to replicate python environment with pytorch and torchvision

### ISSUE THREAD

**Issue by gusido** [allegroai/trains-agent#11]
Hi,
I've tried several combinations of pytorch (1.2, 1.4) and cuda (10,10.1,10.2), and running train-agent using docker and without docker. In all of the cases I get a similar error of the type:
`Exception when trying to resolve python wheel: Was not able to find pytorch wheel URL: Could not find wheel for "torchvision==0.4.0", Available versions: ['1.0.0', '1.0.1', '1.1.0', '1.2.0']`
be it for torch or torch vision.
I also get errors stating cuda 10.1 and cuda 10.2 are not supported.
for reference, please see two attached logs.
[task_a241d53e9593473a858287113ac69cb0.log](https://github.com/allegroai/trains-agent/files/4318433/task_a241d53e9593473a858287113ac69cb0.log)
[task_53b1efb08826447985df4e902c35c6a0.log](https://github.com/allegroai/trains-agent/files/4318439/task_53b1efb08826447985df4e902c35c6a0.log)

thank you!

**Comment by bmartinn** [comment]
Hi @gusido,

What trains-agent version are you using? What is your cuda version?
If you can, please share any other relevant version information.

**Comment by gusido** [comment]
Hi @bmartinn ,sure:

trains-agent version: 0.13.3
trains-server version: 0.14
docker version: 19.03.7, build 7141c199a2
docker image cuda versions that i tried: 10.0,10.1,10.2
installed cuda version on the agent machine: 10.1.105
python version: 3.6.9
OS:  Ubuntu 18.04.4 LTS

**Comment by bmartinn** [comment]
Hi @gusido,

Strange - I can't seem to reproduce this issue here - both `torch==1.4.0` and `torchvision==0.4.0` are resolved and the correct wheel is downloaded and installed.
Is there any chance that trains-agent is unable to reach https://download.pytorch.org/whl/cu101/torch_stable.html from inside the docker?

**Comment by bmartinn** [comment]
Hi @gusido ,

I'll release an RC soon with more visible wheel resolution results, but for now you can simply try editing your experiment installed packages section in the UI and using the specific wheel URL (such as `https://download.pytorch.org/whl/cu101/torch-1.4.0-cp36-cp36m-linux_x86_64.whl`) instead of the torch/torchvision dependency - let me know if that works out for you...

**Comment by gusido** [comment]
hi @bmartinn,

It seems that my firewall is blocking access to https://download.pytorch.org, I'll update once i know for sure. 
In any case, it would be great to have more visible wheel resolution results.

**Comment by gusido** [comment]
Hi @bmartinn ,

Indeed the failure originated from the firewall which re-encrypts the ssl packages.
I can this of a couple of options to overcome this:

- add pip.conf with trusted-host field to the newly create virtualenv
- add ca root certificate to the virtualenv store via certifi
- add --trusted-host flag to the pip command line arguments

for the first two I think I need to create a custom docker image , which i prefer not to do

so a few solutions come to mind:
1 . add a command line argument (flag + value) to the pip calls generated by trains-agent
2. supply the agent with a python script to run somewhere in the virtualenv creation process
3. when parsing the experiment environment - include the environment pip.conf file as well and copy it to the temporary environment created by the agent.

is it possible to implement any of these suggestions? or maybe you have better ones?

**Comment by bmartinn** [comment]
Hi @gusido 

I think the easiest way to fix the SSL certificate problem, is by setting the `REQUESTS_CA_BUNDLE` os environment variable to point to the correct certificate file.

It should solve both python requests issues, and pip install at the same time.

If you are working in virtual-environment mode then you could simply do:

Since *trains-agent* spins all other processes as sub-processes they will inherit the os environment pointing to the correct certificate.

```console
REQUESTS_CA_BUNDLE=~/cert.pem trains-agent daemon --queue default
```

If you are working in a docker mode, you need to add it in the `~/trains.conf` file ([example](https://github.com/allegroai/trains-agent/blob/master/docs/trains.conf#L92)):

Notice we need to first mount the certificate into the docker, and then set the OS environment to point to it. These docker arguments will be added to any docker running on this specific machine, so once setup, you will still be able to switch to different docker images or add additional arguments without any issues.

```console
agent.extra_docker_arguments: ["-e",  "REQUESTS_CA_BUNDLE=/root/cert.pem", "-v", "~/cert.pem:/root/cert.pem"]
```

What do you think?

**Comment by gusido** [comment]
Hi @bmartinn,

your suggestion worked (mounting certificate on docker and setting environment variable). 

thank you!
