### ISSUE TITLE
Conda environment installation skipping packages

### ISSUE THREAD

**Issue by Mert-Ergin** [allegroai/trains-agent#24]
Copied packages do not reflect the environment the copied experiment has been run. I am working with tensorflow-gpu installed with conda but trains does not detect tensorflow-gpu as a package. Below is the `conda list` output 

```
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_tflow_select             2.1.0                       gpu  
absl-py                   0.9.0                    py36_0  
astor                     0.8.0                    py36_0  
attrs                     19.3.0                   pypi_0    pypi
blas                      1.0                         mkl  
c-ares                    1.15.0            h7b6447c_1001  
ca-certificates           2020.1.1                      0  
certifi                   2020.4.5.2               py36_0  
cloudpickle               1.4.1                    pypi_0    pypi
cudatoolkit               10.0.130                      0  
cudnn                     7.6.5                cuda10.0_0  
cupti                     10.0.130                      0  
cycler                    0.10.0                   pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
efficientnet              1.0.0                    pypi_0    pypi
funcsigs                  1.0.2                    pypi_0    pypi
furl                      2.1.0                    pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
gast                      0.3.3                      py_0  
grpcio                    1.27.2           py36hf8bcb03_0  
h5py                      2.10.0           py36h7918eee_0  
hdf5                      1.10.4               hb1b8bf9_0  
horovod                   0.19.4                   pypi_0    pypi
humanfriendly             8.2                      pypi_0    pypi
image-classifiers         1.0.0                    pypi_0    pypi
imageio                   2.8.0                    pypi_0    pypi
imgviz                    1.1.0                    pypi_0    pypi
intel-openmp              2020.1                      217  
joblib                    0.15.1                   pypi_0    pypi
jsonmodels                2.4                      pypi_0    pypi
jsonschema                3.2.0                    pypi_0    pypi
keras                     2.2.4                    pypi_0    pypi
keras-applications        1.0.8                      py_0  
keras-preprocessing       1.1.0                      py_1  
kito                      1.0.4                    pypi_0    pypi
kiwisolver                1.2.0                    pypi_0    pypi
labelme                   3.16.3                   pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.3                  he6710b0_1  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libprotobuf               3.12.3               hd408876_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
markdown                  3.1.1                    py36_0  
matplotlib                3.2.1                    pypi_0    pypi
mkl                       2020.1                      217  
mkl-service               2.3.0            py36he904b0f_0  
mkl_fft                   1.0.15           py36ha843d7b_0  
mkl_random                1.1.1            py36h0573a6f_0  
mock                      4.0.2                      py_0  
ncurses                   6.2                  he6710b0_1  
networkx                  2.4                      pypi_0    pypi
numpy                     1.18.1           py36h4f9e942_0  
numpy-base                1.18.1           py36hde5b4d6_1  
nvidia-dali               0.21.0                   pypi_0    pypi
opencv-python             4.2.0.32                 pypi_0    pypi
openssl                   1.1.1g               h7b6447c_0  
orderedmultidict          1.0.1                    pypi_0    pypi
pathlib2                  2.3.5                    pypi_0    pypi
pillow                    7.1.2                    pypi_0    pypi
pip                       20.0.2                   py36_3  
plotly                    4.8.1                    pypi_0    pypi
protobuf                  3.12.3           py36he6710b0_0  
pyjwt                     1.7.1                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pyqt5                     5.15.0                   pypi_0    pypi
pyqt5-sip                 12.8.0                   pypi_0    pypi
pyrsistent                0.16.0                   pypi_0    pypi
python                    3.6.10               h7579374_2  
pywavelets                1.1.1                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
readline                  8.0                  h7b6447c_0  
requests-file             1.5.1                    pypi_0    pypi
retrying                  1.3.3                    pypi_0    pypi
scikit-image              0.17.2                   pypi_0    pypi
scikit-learn              0.21.0                   pypi_0    pypi
scipy                     1.4.1            py36h0b6359f_0  
segmentation-models       1.0.1                    pypi_0    pypi
setuptools                47.1.1                   py36_0  
six                       1.15.0                     py_0  
sqlite                    3.31.1               h62c20be_1  
tensorboard               1.13.1           py36hf484d3e_0  
tensorflow                1.13.1          gpu_py36h3991807_0  
tensorflow-base           1.13.1          gpu_py36h8d69cac_0  
tensorflow-estimator      1.13.0                     py_0  
tensorflow-gpu            1.13.1               h0d30ee6_0  
termcolor                 1.1.0                    py36_1  
tifffile                  2020.6.3                 pypi_0    pypi
tk                        8.6.8                hbc83047_0  
tqdm                      4.46.1                   pypi_0    pypi
trains                    0.15.0                   pypi_0    pypi
typing                    3.7.4.1                  pypi_0    pypi
werkzeug                  1.0.1                      py_0  
wheel                     0.34.2                   py36_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
```

However in dashboard tensorflow-gpu does not show in installed packages:
```

# Python 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21)  [GCC 7.3.0]

Keras == 2.2.4
Keras_Applications == 1.0.8
Pillow == 7.1.2
efficientnet == 1.0.0
h5py == 2.10.0
horovod == 0.19.4
image_classifiers == 1.0.0
imageio == 2.8.0
imgviz == 1.1.0
kito == 1.0.4
labelme == 3.16.3
matplotlib == 3.2.1
numpy == 1.18.4
nvidia_dali == 0.21.0
opencv_python == 4.2.0.32
scikit_image == 0.17.2
scikit_learn == 0.21.0
tensorflow == 1.13.1
tqdm == 4.46.1
trains == 0.15.0


```

It only captures tensorflow which eventually trains on CPU. This is also true for other conda packages. Package manager.type is set to conda for trains-agent config. 

`agent.package_manager.type = conda`

Here is the part of the results where agent tries to install conda requirements. As you can see many of the packages are missing.
```

Conda: Trying to install requirements:
['h5py~=2.10.0', 'Keras-Applications~=1.0.8', 'numpy~=1.18.4', 'tensorflow~=1.13.1', 'graphviz', 'python-graphviz', 'kiwisolver', 'cpuonly']
Executing Conda: /home/mert/anaconda3/condabin/conda env update -p /home/mert/.trains/venvs-builds-alsi/3.6 --file /tmp/conda_envbjjg4czh.yml --quiet --json

```

Thank you for your help in advance. Attached a bash script to replicate the environment. Discarded horovod part as it requires openmpi, nccl etc.

[condainstallscript.sh.txt](https://github.com/allegroai/trains-agent/files/4788387/condainstallscript.sh.txt)

**Comment by bmartinn** [comment]
Hi @Mert-Ergin ,
*Trains* will catch and enlist packages you specifically import from your code.
The reason Trains does not capture the entire conda/pip environment, is to allow the *trains-agent* more "freedom" when it re-creates the environment. That said once the *trains-agent* creates the new environment it will update back **all** the installed packages, including derivative packages.

Specifically `tensorflow` will always show as `tensorflow` with a specific version, then *trains-agent* depending on its setup will wither install `tensorflow` (if it is running with cpu-only settings, or `tensorflow-gpu` if running in gpu mode)

> Conda: Trying to install requirements:
['h5py~=2.10.0', 'Keras-Applications~=1.0.8', 'numpy~=1.18.4', 'tensorflow~=1.13.1', 'graphviz', 'python-graphviz', 'kiwisolver', 'cpuonly']
Executing Conda: /home/mert/anaconda3/condabin/conda env update -p /home/mert/.trains/venvs-builds-alsi/3.6 --file /tmp/conda_envbjjg4czh.yml --quiet --json

It seems *trains-agent* thinks it is in `cpu-only` mode, which is the reason it is trying to install tensroflow and not tensorflow-gpu (actually with conda this is set by defining the conda environment, see the `cpuonly` argument at the end of the command line)

Once the installation is done, the *trains-agent* will update back the experiment with all the installed packages (because this is by definition a clean environment that can be fully reproduced)

What's the *trains-agent* command like you are using ? Did you add `--gpu all`

BTW:
If you clone the experiment (right-click select "Clone") you can edit the "Installed Packages" list and add any package that *trains* missed (hopefully that should not happen :)

**Comment by Mert-Ergin** [comment]
> _Trains_ will catch and enlist packages you specifically import from your code.
> The reason Trains does not capture the entire conda/pip environment, is to allow the _trains-agent_ more "freedom" when it re-creates the environment. That said once the _trains-agent_ creates the new environment it will update back **all** the installed packages, including derivative packages.
> Specifically `tensorflow` will always show as `tensorflow` with a specific version, then _trains-agent_ depending on its setup will wither install `tensorflow` (if it is running with cpu-only settings, or `tensorflow-gpu` if running in gpu mode)

I understand this decison and respect it. However, it is not capturing the right packages in conda when both conda and pip packages are installed. I tried this without horovod installed and it is the same. By the way I don't think agents is the problem. Because this also happens for the original training. Only a couple of the packages are detected. And I am sure the original training is using tensorflow-gpu as I checked from nvidia-smi and all were occupied. 
> 
> > Conda: Trying to install requirements:
> > ['h5py~=2.10.0', 'Keras-Applications~=1.0.8', 'numpy~=1.18.4', 'tensorflow~=1.13.1', 'graphviz', 'python-graphviz', 'kiwisolver', 'cpuonly']
> > Executing Conda: /home/mert/anaconda3/condabin/conda env update -p /home/mert/.trains/venvs-builds-alsi/3.6 --file /tmp/conda_envbjjg4czh.yml --quiet --json
> It seems _trains-agent_ thinks it is in `cpu-only` mode, which is the reason it is trying to install tensroflow and not tensorflow-gpu (actually with conda this is set by defining the conda environment, see the `cpuonly` argument at the end of the command line)


> Once the installation is done, the _trains-agent_ will update back the experiment with all the installed packages (because this is by definition a clean environment that can be fully reproduced)
> 
> What's the _trains-agent_ command like you are using ? Did you add `--gpu all`

full command is:
`trains-agent daemon --detached --gpus all --queue all`
> 
> BTW:
> If you clone the experiment (right-click select "Clone") you can edit the "Installed Packages" list and add any package that _trains_ missed (hopefully that should not happen :)

I tried this part too. However, conda package part is not even listed there. So I can not add other packages like cudnn cuda-toolkit etc. Additionally if I change the installed packages part how could the software keep track of whether to use pip or conda? 

Am I missing something here? Do I need to restart server after updating config file? Or is conda supported for only a specific version (I am using conda 4.6.11).

**Comment by bmartinn** [comment]
Hi @Mert-Ergin ,
There is a distinction here that is important, there are two types of packages 
- Code defendant packages: such as Keras numpy Tensorflow etc. These Trains will automatically list under "Installed Packages", again without their requirements.
- Environment dependent packages: Such as tensorflow-gpu (vs tensorflow), PyTroch for specific CUDA, and conda specific such as cudnn, cuda-toolkit etc. These packages are installed per machine by the *trains-agent* automatically and depending on the machine setup (i.e. CPU/GPU CUDA version etc.). There is no need to list them, the idea is that if we want to run the same code on a different machine with different CUDA version or on a CPU, it is transparent, the *trains-agent* will take care of it.

Now on how it works:
If *trains-agent* is using conda as the package manager, it will first try to install all the packages using conda. That means that you can add any conda-specific package into the "Installed Packages" and it will get installed (obviously it will not work on machines running an agent with different package manager). That said all the default GPU/CUDA packages should be installed automatically with matching CUDA versions to the system.
BTW: This is the reason tensorflow is listed in the "installed packages" and not "tensorflow-gpu" , the agent will install the "tensorflow-gpu" instead, if it is running with `--gpus` .

Could you send the *trains-agent* output when you execute it, it should output all it's configuration, including the CUDA/CUDNN version it will use to setup conda environment.
Specifically the interesting part is:
```console
agent.package_manager.type = conda
agent.cuda_version = 101
agent.cudnn_version = 76
```

If you it failed automatically detecting the CUDA/CUDNN versions you can specify them in the standard NVIDIA OS environment variables. 
For example:
```
$ CUDA_VERSION=10.0.1 CUDNN_VERSION=7.6 trains-agent daemon --detached --gpus all --queue all
```

If I had to guess, I think the missing CUDA version is the root cause of it all, and I will make sure that if running with conda and CUDA is not detected it will print an error and leave, in order to avoid these situations that are very challenging to debug.
What do you think?

**Comment by Mert-Ergin** [comment]
Hi Martin, 
Figured the problem. Had to restart the agent daemon wtih single gpu. Now it is detecting tensorflow-gpu for both pip and conda environments.  Thank you for your response. I thought workers were updated for each experiment in the queue.
Have a follow up issue about horovod but unrelated to this one.
