### ISSUE TITLE
Error when running experiments using NVIDIA pytorch docker image

### ISSUE THREAD

**Issue by dotannn** [allegroai/trains-agent#3]
Hi,
Recently we switched to running trains-agent tasks using a docker image as a basis, this allowed us to overcome issue #1  regarding apex [that cannot be installed from pypi]. 

We use [NVIDIA's PyTorch container ](https://ngc.nvidia.com/catalog/containers/nvidia:pytorch) and apparently they compiled their own version of PyTorch using a version tag that is not included in PyPI [version torch 1.4.0a0+649135b   where the latest released version of PyTorch is 1.3.2]

To avoid conflicts and because we're using the docker image as a base now, we removed "torch" from our requirement.txt file.  but - due to trains-agent magic package-requirement logging, the package is added to the required packages of the task. then when we're trying to run a cloned task, the trains-agent tries to install the 'unique' versions of PyTorch and the task crashes/fails.

This is also happening in NVIDIA's version of torchvision [torchvision 0.5.0a0]

How do you suggest to tackle this issue?

**Comment by bmartinn** [comment]
Hey @dotannn, 

Luckily we run into the same issue with torch packages :)

This issue is specific to torch packages, since the *trains-agent* will look for the correct wheel distro to install (based on the pytorch.org install matrix), matching the CUDA version available inside the docker/virtual-environment.

Since the requested package version is nowhere to be found (even though installed) it would fail.

There is already an RC with initial fix, feel free to test it:
`$ pip install trains-agent==0.12.3rc0`

**Comment by dotannn** [comment]
Thanks, it worked!
