### ISSUE TITLE
getting all monitor metrics for a task from the api

### ISSUE THREAD

**Issue by Cptmaxon** [allegroai/trains-agent#4]
Hello , 
we would like to get the timeseries of all scalars plots, not the hardware ones, just the ones for loss val_roc and such per iteration, the use case is an automatic process that follows experiments to see that they converage towards the same point .
thanks

**Comment by bmartinn** [comment]
Hi @Cptmaxon ,

In order to do that you will first need to upgrade to the latest RC:
`$ pip install trains-agent==0.12.3rc1`

Then you can use the following code to get all scalar metrics for a specific experiment, where "AABB1122" is your experiment ID.
`data.metric` is a nested dictionary holding the scalar time series plots (x/y)

```python
from trains_agent import APIClient

api_client = APIClient()
data = api_client.events.scalar_metrics_iter_histogram(task="AABB1122")
print(data.metrics)
```
